insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Abdominal CT (computed tomography) scan');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Abdominal Ultrasound');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Amniocentesis');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Arterial blood flow studies of the legs (Segmental Doppler Pressures)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Anoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Back x-rays (or spine x-rays)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Barium enema');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Barium swallow (or upper gastrointestinal or &quot;UGI series&quot;)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Bone density test for osteoporosis');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Bone marrow biopsy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Bone scan');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Breast ultrasound');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Bronchoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Cardiac catheterization');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Carotid ultrasound (carotid doppler)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Chest x-ray');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Chorionic villus sampling');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Colonoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Colposcopy and cervical biopsy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Computer tomography (CT) for abdomen');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Computed tomography (CT) for back problems');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Cystoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Cystourethrogram');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Echocardiogram');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Electrocardiogram');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Electromyography and nerve conduction studies');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Electrophysiological (EP) testing of the heart');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Endometrial biopsy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Endoscopic retrograde cholangiopancreatography (ERCP)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Enhanced alpha fetoprotein test (&quot;Triple Screen&quot;)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Excisional biopsy of the breast');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Exercise stress test');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Fecal occult blood (FOB) test');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Fetal ultrasound');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Fine-needle aspiration (FNA) of the breast');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Flexible sigmoidoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Fluorescein angiography (for diabetic retinopathy)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Holter monitor');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Hysterosalpingogram');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Hysteroscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Intravenous pyelogram');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Kidney biopsy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Laparoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Liver biopsy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Lower extremity doppler (Venous ultrasound of the legs)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Lumbar puncture (or spinal tap)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Lymph node biospy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Magnetic resonance image (MRI) of the brain');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Magnetic resonance image (MRI) of the spine');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Mammogram');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Mediastinoscopy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Myelography');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Oxygen saturation test');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Pap smear');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Pelvic ultrasound and transvaginal ultrasound');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Percutaneous transhepatic cholangiography (PTCA)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Pleural fluid sampling (or thoracentesis)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('PSA (prostate specific-antigen) test');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Pulmonary angiography');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Pulmonary function testing');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Radionuclide scan of the kidneys');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Rapid Strep test');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Scratch test for allergies');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Segmental Doppler Pressures (Arterial blood flow studies of the legs)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Skin biopsy');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Snellen test for visual acuity');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Spinal tap (or lumbar puncture)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Spine x-rays (or back x-rays)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Sputum evaluation (and sputum induction)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Stereotactic biopsy of the breast (breast core biopsy)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Testing for vaginitis (yeast infections, trichomonas, and gardnerella)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Thoracentesis (or pleural fluid sampling)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Throat culture');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Thyroid scan');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Tonometry');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Transrectal ultrasound and biopsy of the prostate');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Triple screen test (or enhanced alpha fetoprotein test)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Tuberculosis (TB) skin test');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Upper endoscopy (or esophagogastroduodenoscopy)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Upper gastrointestinal series, or UGI series (or barium swallow)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Urinalysis');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Ventilation-perfusion (or &quot;V-Q&quot; scan)');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Video-assisted thoracic surgery');
insert into `mediapp`.`test_meta_data` ( `test_description`) values ('Wire localization biopsy of the breast');
commit;